# init ubuntu
FROM ubuntu:latest

# download git and update packages
RUN apt-get update && apt-get install -y git

# change workdir
WORKDIR /warehouse

# clone the 'dev-q3' branch of the warehouse repo from GitHub
RUN git clone --branch dev-q3 https://github.com/ifheroes/warehouse.git

# install php and apache webserver
RUN apt-get update && apt-get install -y \
    apache2 \
    php \
    libapache2-mod-php \
    jq && \
    a2enmod rewrite && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Remove the default Apache index.html page
RUN rm -rf /var/www/html/*

# Move the cloned warehouse repository to the Apache web directory
RUN mv /warehouse/warehouse/* /var/www/html/

# Configure Apache on the port for api access
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf && \
    sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf && \
    sed -i 's/<VirtualHost \*:80>/<VirtualHost \*:8080>/' /etc/apache2/sites-available/000-default.conf

# Copy the config file into the container (overwrite default configuration)
COPY ./config.json /var/www/html/config.json

# Expose port 8080 for Apache
EXPOSE 8080

# Start Apache in the foreground (necessary for the container to keep running)
CMD ["apache2ctl", "-D", "FOREGROUND"]
