version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./config.json:/var/www/html/config.json
